name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user poetry==2.2.1
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Poetry version
        run: poetry --version

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Lint
        run: poetry run ruff check

      - name: Test
        run: poetry run pytest
